package net.rooms.RoomsServer.message;

public enum MessageType {
	MESSAGE,
	PONG_GAME_OPEN,
	PONG_GAME_ABORT,
	PONG_GAME_ONGOING,
	PONG_GAME_RESULT,
	SNAKES_GAME_OPEN,
	SNAKES_GAME_ABORT,
	SNAKES_GAME_ONGOING,
	SNAKES_GAME_RESULT
}
